version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    allow:
      - dependency-type: "direct"
    security-updates-only: true

  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    allow:
      - dependency-type: "direct"
    security-updates-only: true

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    allow:
      - dependency-type: "direct"
    security-updates-only: true

  - package-ecosystem: "npm"
    directory: "/packages/data-provider"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    allow:
      - dependency-type: "direct"
    security-updates-only: true