version: "3.4"

services:
  api:
    ports:
      - 3080:3080
    depends_on:
      - mongodb
    image: node-api
    build:
      context: .
      target: node-api
    restart: always
    env_file:
      - ./api/.env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/chatgpt-clone
    volumes:
      - ./api:/api
      - /api/node_modules
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
