version: '3'
services:
  meilisearch:
    image: getmeili/meilisearch:v1.0
    ports:
      - 7700:7700
    environment:
      - MEILI_MASTER_KEY=MASTER_KEY
    volumes:
      - ./meili_data:/meili_data