# Project information
site_name: Librechat

# Repository
repo_name: danny-avila/LibreChat
repo_url: https://github.com/danny-avila/LibreChat
edit_uri: ''

theme:
  name: material
  logo: assets/logo.png
  
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  
  icon:
    repo: fontawesome/brands/gitlab
    edit: material/pencil
    view: material/eye
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.action.edit
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/CEe6vDg9Ky
    - icon: fontawesome/brands/github
      link: https://github.com/danny-avila/LibreChat
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@LibreChat

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


# Page tree
nav:
  - Home: 'index.md'
  - Getting Started: 
    - Docker Install: 'install/docker_install.md'
    - Linux Install: 'install/linux_install.md'
    - Mac Install: 'install/mac_install.md'
    - Windows Install: 'install/windows_install.md'
    - APIs and Tokens: 'install/apis_and_tokens.md'
  - General Information:
    - Project Origin: 'general_info/project_origin.md'
    - Multilingual Information: 'general_info/multilingual_information.md'
    - Tech Stack: 'general_info/tech_stack.md'
    - Bing Jailbreak Info: 'general_info/bing_jailbreak_info.md'
  - Features:
    - Plugins:
      - Introduction: 'features/plugins/introduction.md'
      - Google: 'features/plugins/google_search.md'
      - Stable Diffusion: 'features/plugins/stable_diffusion.md'
      - Wolfram: 'features/plugins/wolfram.md'
      - Make Your Own Plugin: 'features/plugins/make_your_own.md'
    - User Auth System: 'features/user_auth_system.md'
    - Proxy: 'features/proxy.md'
  - Cloud Deployment:
    - Hetzner: 'deployment/hetzner_ubuntu.md'
    - Heroku: 'deployment/heroku.md'
    - Cloudflare: 'deployment/cloudflare.md'
    - Linode: 'deployment/linode.md'
  - Contributions:
    - Documentation Guidelines: 'contributions/documentation_guidelines.md'
    - Code Standards and Conventions: 'contributions/coding_conventions.md'
    - Testing: 'contributions/testing.md' 

