name: Docker Compose Build Latest Main Image Tag (Manual Dispatch)

# The workflow is manually triggered
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch tags and set the latest tag
        run: |
          git fetch --tags
          echo "LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata for librechat
        id: meta-librechat
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/librechat
          tags: |
            type=raw,value=${{ env.LATEST_TAG }},enable=true
            type=raw,value=latest,enable=true
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      # Adjusted to correct the command and include retry logic
      - name: Build and push librechat with retry
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 20
          max_attempts: 3
          command: |
            docker buildx build \
              --file Dockerfile \
              --push \
              $(echo "${{ steps.meta-librechat.outputs.tags }}" | sed "s/,/ --tag /g" | xargs echo --tag) \
              --platform linux/amd64,linux/arm64 \
              --target node \
              .
