name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  tests_e2e:
    name: Run end-to-end tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install API dependencies
      working-directory: ./api
      run: npm ci

    - name: Install Client dependencies
      working-directory: ./client
      run: npm ci

    - name: Start API server
      working-directory: ./api
      run: |
        npm run start &
        sleep 10 # Wait for the server to start

    - name: Build Client
      working-directory: ./client
      run: npm run build

    - name: Install global dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: e2e/playwright-report/
        retention-days: 30
